ex_grumpy_homepage:
    path:     /
    defaults: { _controller: EXGrumpyBundle:Forum:index }

ex_grumpy_subscribe:
    path:     /subscribe_event/{event_id}
    defaults: { _controller: EXGrumpyBundle:Event:subscribe_event }
    requirements:
        event_id: '\d+'

ex_grumpy_like:
    path:     /like_event/{event_id}
    defaults: { _controller: EXGrumpyBundle:Event:like_event }
    requirements:
        event_id: '\d+'

ex_grumpy_boite_idees:
    path:     /boite_idees
    defaults: { _controller: EXGrumpyBundle:Event:view_idee }

ex_grumpy_evenements:
    path:     /evenements
    defaults: { _controller: EXGrumpyBundle:Event:view_events }

ex_grumpy_add_event:
    path:     /add_event
    defaults: { _controller: EXGrumpyBundle:Event:add_event }

ex_grumpy_view_event:
    path:     /view_event/{event_id}
    defaults: { _controller: EXGrumpyBundle:Event:view }
    requirements:
        event_id: '\d+'

ex_grumpy_add_comment:
    path:     /add_comment/{event_id}/{cat_comment}
    defaults: {_controller: EXGrumpyBundle:Event:add_commentaire}
    requirements:
        event_id: '\d+'
        cat_comment: like|dislike|commentaire|image  

ex_grumpy_view_comments_by_event:
    path:     /view_comments/{event_id}
    defaults: { _controller: EXGrumpyBundle:Event:view_comments_by_event }

ex_grumpy_add_product:
    path:     /add_product
    defaults: { _controller: EXGrumpyBundle:Shop:add_product }

ex_grumpy_view_products:
    path:     /view_products
    defaults: { _controller: EXGrumpyBundle:Shop:view_products }    

ex_grumpy_view_product:
    path:     /view_product/{product_id}
    defaults: { _controller: EXGrumpyBundle:Shop:view_product }
    requirements:
        event_id: '\d+'

ex_grumpy_add_to_panier:
    path:     /add_to_panier/{product_id}
    defaults: { _controller: EXGrumpyBundle:Shop:add_to_panier }
    requirements:
        event_id: '\d+'

ex_grumpy_view_panier:
    path:    /view_panier
    defaults: { _controller: EXGrumpyBundle:Shop:view_panier }

ex_grumpy_validate_commande:
    path:    /validate_commande
    defaults: { _controller: EXGrumpyBundle:Shop:validate_commande }

ex_grumpy_legal:
    path:    /legal
    defaults: { _controller: EXGrumpyBundle:Forum:view_legal }