ex_grumpy_homepage:
    path:     /
    defaults: { _controller: EXGrumpyBundle:Forum:index }

ex_grumpy_add:
    path:     /add
    defaults: { _controller: EXGrumpyBundle:Forum:add }

ex_grumpy_view:
    path:     /view_event/{event_id}
    defaults: { _controller: EXGrumpyBundle:Forum:view }
    requirements:
        event_id: '\d+'

ex_grumpy_subscribe:
    path:     /subscribe_event/{event_id}
    defaults: { _controller: EXGrumpyBundle:Forum:subscribe_event }
    requirements:
        event_id: '\d+'

ex_grumpy_boite_idees:
    path:     /boite_idees
    defaults: { _controller: EXGrumpyBundle:Forum:view_idee }

ex_grumpy_evenements:
    path:     /evenements
    defaults: { _controller: EXGrumpyBundle:Forum:view_events }

ex_grumpy_add_event:
    path:     /add_event
    defaults: { _controller: EXGrumpyBundle:Forum:add_event }

ex_grumpy_view_event:
    path:     /view_event
    defaults: { _controller: EXGrumpyBundle:Forum:view_event }

ex_grumpy_add_comment:
    path:     /add_comment/{cat_comment}
    defaults: {_controller: EXGrumpyBundle:Forum:add_commentaire}
    requirements:
        cat_comment: like|dislike|commentaire|image  

ex_grumpy_view_event:
    path:     /view_comment
    defaults: { _controller: EXGrumpyBundle:Forum:view_comment }

ex_grumpy_add_product:
    path:     /add_product
    defaults: { _controller: EXGrumpyBundle:Forum:add_product }

ex_grumpy_view_products:
    path:     /view_products
    defaults: { _controller: EXGrumpyBundle:Forum:view_products }    

ex_grumpy_view_product:
    path:     /view_product/{product_id}
    defaults: { _controller: EXGrumpyBundle:Forum:view_product }
    requirements:
        event_id: '\d+'