ex_grumpy_homepage:
    path:     /
    defaults: { _controller: EXGrumpyBundle:Forum:index }

ex_grumpy_add:
    path:     /add_event
    defaults: { _controller: EXGrumpyBundle:Forum:add_event }

ex_grumpy_view:
    path:     /view_event
    defaults: { _controller: EXGrumpyBundle:Forum:view_event }